### PR TITLE
added new platform svg links

### PR DESCRIPTION
**Pull request by pcDamasceno**
Added links to :[telegram, whatsapp, snapchat, spotify, flickr, vimeo, stackoverflow, skype, sclack]

Also, added tabs to __get_platform_svg() on color for better visualization

### CODE REVIEW

**Comment by pcDamasceno** [comment]
Rearranged items in alphabetical order to make it easier to find platforms.

**Comment by pcDamasceno** [comment]
added tradingview svg icon

**Comment by jlnetosci** [comment]
Hi Pedro. Thanks for your contribution! I will review it thoroughly when I have some availability. 

I have never gotten requests for any of those platforms (I'll take this as your suggestion for adding them though), even though I am not sure some are useful for streamlit developers.

Currently the platforms are ordered by [monthly active users](https://en.wikipedia.org/wiki/List_of_social_platforms_with_at_least_100_million_active_users), which is more intuitive for me as the maintainer, adding your suggestions I will probably also switch to alphabetical.

Buy me a coffee already has a better implementation on [streamlit-extras](https://arnaudmiribel.github.io/streamlit-extras/extras/buy_me_a_coffee/), but redundancy is fine.

**Comment by jlnetosci** [comment]
@pcDamasceno, I accepted your suggestions, but will not be merging the PR directly. I opted to add them as my own commits and commit messages for clarity, and corrected some colors to follow branding guidelines. 

I have updated to v0.1.4. Your name and username are present in the Acknowledgments section starting with this version. Cheers.

**Pull request closed without merging**
